<a href="https://colab.research.google.com/github/KRiver28/TIL/blob/master/%ED%85%8D%EC%8A%A4%ED%8A%B8%EC%9C%A0%EC%82%AC%EB%8F%84.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Tfidf를 이용한 유사도 측정 예시
# 유사도 : 자카드, 코사인, 유클리디언, 맨하탄 유사도
# ------------------------------------------------
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer

In [2]:
sent = ("휴일 인 오늘 도 서쪽 을 중심 으로 폭염 이 이어졌는데요, 내일 은 반가운 비 소식 이 있습니다.", 
        "폭염 을 피해서 휴일 에 놀러왔다가 갑작스런 비 로 인해 망연자실 하고 있습니다.")

In [3]:
# 1. 자카드 유사도
# ----------------
sent_1 = set(sent[0].split())
sent_2 = set(sent[1].split())
print(sent_1)
print(sent_2)

{'오늘', '폭염', '있습니다.', '인', '비', '소식', '반가운', '도', '으로', '내일', '이어졌는데요,', '서쪽', '을', '중심', '이', '은', '휴일'}
{'폭염', '하고', '있습니다.', '비', '망연자실', '로', '피해서', '갑작스런', '을', '에', '놀러왔다가', '휴일', '인해'}


In [4]:
# 합집합과 교집합을 구한다.
hap_set = sent_1 | sent_2
gyo_set = sent_1 & sent_2
print()
print(hap_set, '\n')
print(gyo_set, '\n')

jaccard = len(gyo_set) / len(hap_set)
print(jaccard)

tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(sent).toarray()
print(np.round(tfidf_matrix, 3))

idf = tfidf_vectorizer.idf_
print(dict(zip(tfidf_vectorizer.get_feature_names(), idf))) # 각 수치에 대한 값 시각화


{'오늘', '하고', '인', '비', '로', '도', '으로', '피해서', '휴일', '서쪽', '을', '중심', '이', '에', '소식', '인해', '폭염', '있습니다.', '망연자실', '반가운', '내일', '갑작스런', '이어졌는데요,', '놀러왔다가', '은'} 

{'폭염', '있습니다.', '비', '을', '휴일'} 

0.2
[[0.    0.324 0.    0.    0.324 0.324 0.324 0.324 0.324 0.324 0.    0.231
  0.324 0.231 0.    0.    0.231]
 [0.365 0.    0.365 0.365 0.    0.    0.    0.    0.    0.    0.365 0.259
  0.    0.259 0.365 0.365 0.259]]
{'갑작스런': 1.4054651081081644, '내일': 1.4054651081081644, '놀러왔다가': 1.4054651081081644, '망연자실': 1.4054651081081644, '반가운': 1.4054651081081644, '서쪽': 1.4054651081081644, '소식': 1.4054651081081644, '오늘': 1.4054651081081644, '으로': 1.4054651081081644, '이어졌는데요': 1.4054651081081644, '인해': 1.4054651081081644, '있습니다': 1.0, '중심': 1.4054651081081644, '폭염': 1.0, '피해서': 1.4054651081081644, '하고': 1.4054651081081644, '휴일': 1.0}


/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [5]:
# 2. 코사인 유사도
# ---------------
from sklearn.metrics.pairwise import cosine_similarity

d = cosine_similarity(tfidf_matrix[0:1], tfidf_matrix[1:2])
print(d)

[[0.17952266]]


In [6]:
# 3. 유클리디안 유사도
# -------------------
from sklearn.metrics.pairwise import euclidean_distances

euclidean_distances(tfidf_matrix[0:1], tfidf_matrix[1:2])

array([[1.28099753]])

In [7]:
# 정규화
def l1_normalize(v):
    return v / np.sum(v)

tfidf_norm_l1 = l1_normalize(tfidf_matrix)
euclidean_distances(tfidf_norm_l1[0:1], tfidf_norm_l1[1:2])

array([[0.20491229]])

In [8]:
# 4. 맨하탄 유사도
# ---------------
from sklearn.metrics.pairwise import manhattan_distances

manhattan_distances(tfidf_norm_l1[0:1], tfidf_norm_l1[1:2])

array([[0.77865927]])